FROM docker.arvancloud.ir/library/python:3.11-slim

WORKDIR /app

# Install system build dependencies for librdkafka
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libc-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "-u", "main.py"]